package org.openmrs.module.openmrseventrecords.web.resource;

import org.openmrs.api.context.Context;
import org.openmrs.module.openmrseventrecords.EventRecord;
import org.openmrs.module.openmrseventrecords.api.EventRecordService;
import org.openmrs.module.webservices.rest.web.RequestContext;
import org.openmrs.module.webservices.rest.web.RestConstants;
import org.openmrs.module.webservices.rest.web.annotation.Resource;
import org.openmrs.module.webservices.rest.web.representation.DefaultRepresentation;
import org.openmrs.module.webservices.rest.web.representation.RefRepresentation;
import org.openmrs.module.webservices.rest.web.representation.Representation;
import org.openmrs.module.webservices.rest.web.resource.impl.DelegatingCrudResource;
import org.openmrs.module.webservices.rest.web.resource.impl.DelegatingResourceDescription;
import org.openmrs.module.webservices.rest.web.resource.impl.NeedsPaging;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

@Resource(name = RestConstants.VERSION_1 + "/eventrecord", supportedClass = EventRecord.class, supportedOpenmrsVersions = {"2.7.*"})
public class EventRecordResource extends DelegatingCrudResource<EventRecord> {

    protected static final Log log = LogFactory.getLog(EventRecordResource.class);

    @Override
    public EventRecord getByUniqueId(String uuid) {
        return getService().getEventRecordByUuid(uuid);
    }

    @Override
    public EventRecord save(EventRecord eventRecord) {
        // Typically, EventRecords are generated by the system, not created via REST.
        // If you intend for this endpoint to be read-only for new records,
        // you might throw an UnsupportedOperationException here, or simply return null.
        // For a read-only endpoint, you might remove the save method completely.
        // If you keep it, be mindful you are interacting with a core OpenMRS table.
        return getService().saveEventRecord(eventRecord);
    }

    @Override
    public EventRecord newDelegate() {
        return new EventRecord();
    }

    @Override
    public void purge(EventRecord eventRecord, RequestContext context) {
        // Similar to save, purging core event records is generally not advised via a module.
        // Consider removing this method if the module is read-only.
        getService().deleteEventRecord(eventRecord);
    }

    @Override
    public void delete(EventRecord eventRecord, String reason, RequestContext context) {
        if (eventRecord == null) {
            throw new IllegalArgumentException("No EventRecord found with the provided ID");
        }
        // Similar to purge, consider removing if module is read-only.
        getService().deleteEventRecord(eventRecord);
    }

    @Override
    public String getUniqueId(EventRecord eventRecord) {
        return eventRecord.getUuid();
    }

    @Override
    public DelegatingResourceDescription getRepresentationDescription(Representation rep) {
        DelegatingResourceDescription description = new DelegatingResourceDescription();

        if (rep instanceof DefaultRepresentation) {
            description.addProperty("uuid");
            description.addProperty("id"); // Include the internal ID for convenience
            description.addProperty("title");
            description.addProperty("timestamp");
            description.addProperty("uri");
            description.addProperty("object"); // Expose the JSON string
            description.addProperty("category");
            description.addProperty("dateCreated"); // Changed from "eventDateCreated" to match EventRecord.java
            description.addProperty("tags");

            // Removed comments about BaseOpenmrsData properties as we no longer extend it.
        } else if (rep instanceof RefRepresentation) {
            description.addProperty("uuid");
            description.addProperty("title");
            description.addProperty("category");
        }

        description.addSelfLink();
        return description;
    }

    @Override
    public DelegatingResourceDescription getCreatableProperties() {
        // For event_records, you might not allow creation via REST.
        // Event records are typically created by the system, not directly by users/modules.
        // If you do allow creation, ensure these fields are actually mutable/creatable for event_records.
        DelegatingResourceDescription description = new DelegatingResourceDescription();
        // UUID is usually auto-generated by the system, so making it required for creation might be problematic
        // if the client is not expected to provide it.
        // description.addRequiredProperty("uuid");
        description.addRequiredProperty("title");
        description.addRequiredProperty("timestamp");
        description.addRequiredProperty("category");
        // 'object', 'uri', 'tags' might be optional
        description.addProperty("uri");
        description.addProperty("object");
        description.addProperty("tags");
        return description;
    }

    @Override
    public NeedsPaging<EventRecord> doGetAll(RequestContext context) {
        // You can add filtering capabilities here based on request parameters
        // Example: /ws/rest/v1/eventrecord?category=patient&startDate=2024-01-01&endDate=2024-12-31
        String category = context.getParameter("category");
        String title = context.getParameter("title");
        String startDateStr = context.getParameter("startDate");
        String endDateStr = context.getParameter("endDate");

        Date startDate = parseDate(startDateStr);
        Date endDate = parseDate(endDateStr);

        List<EventRecord> records;
        if (category != null) {
            records = getService().getEventRecordsByCategory(category);
        } else if (title != null) {
            records = getService().getEventRecordsByTitle(title);
        } else if (startDate != null || endDate != null) {
            records = getService().getEventRecordsByDateRange(startDate, endDate);
        } else {
            records = getService().getAllEventRecords();
        }
        return new NeedsPaging<>(records, context);
    }

    /**
     * Helper method to parse date strings from request parameters.
     * Assumes a "yyyy-MM-dd" format for simplicity.
     * You might need to adjust the date format based on your API design.
     *
     * @param dateString The date string from the request parameter.
     * @return A Date object, or null if the string is null/empty or cannot be parsed.
     */
    private Date parseDate(String dateString) {
        if (dateString == null || dateString.isEmpty()) {
            return null;
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);

        try {
            return dateFormat.parse(dateString);
        } catch (ParseException e) {
            log.warn("Failed to parse date string '" + dateString + "'. Expected format: " + dateFormat.toPattern(), e);
            return null;
        }
    }

    private EventRecordService getService() {
        return Context.getService(EventRecordService.class);
    }

    @Override
    public DelegatingResourceDescription getUpdatableProperties() {
        // Event records are rarely updated via REST, as they represent historical events.
        // If you allow updates, specify which fields can be updated.
        // For 'event_records', consider if any updates are genuinely supported or if this should be read-only.
        DelegatingResourceDescription description = new DelegatingResourceDescription();
        description.addProperty("title");
        description.addProperty("uri");
        description.addProperty("object");
        description.addProperty("category");
        description.addProperty("tags");
        return description;
    }
}