package org.openmrs.module.openmrseventrecords.db.hibernate;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import org.openmrs.module.openmrseventrecords.EventRecord; // Import new domain object
import org.openmrs.module.openmrseventrecords.db.EventRecordDAO; // Import new DAO interface
import java.util.Date;
import java.util.List;

public class HibernateEventRecordDAOImpl implements EventRecordDAO {

    private SessionFactory sessionFactory;

    public void setSessionFactory(SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }

    @Override
    public EventRecord saveEventRecord(EventRecord eventRecord) {
        // For event_records, you generally won't be saving new ones via a module.
        // These are typically generated by the OpenMRS system itself.
        // If this module is purely for reading, consider removing the save method
        // from the service and DAO interfaces and implementations.
        // If you keep it, be aware you're interacting with a core OpenMRS table.
        sessionFactory.getCurrentSession().saveOrUpdate(eventRecord);
        return eventRecord;
    }

    @Override
    public EventRecord getEventRecordById(Integer id) {
        return (EventRecord) sessionFactory.getCurrentSession().get(EventRecord.class, id);
    }

    @SuppressWarnings("unchecked")
    @Override
    public List<EventRecord> getAllEventRecords() {
        return sessionFactory.getCurrentSession().createCriteria(EventRecord.class).list();
    }

    @Override
    public void deleteEventRecord(EventRecord eventRecord) {
        // Similar to save, deletion of core event records is usually not done via a module.
        // Consider removing this method if the module is read-only.
        sessionFactory.getCurrentSession().delete(eventRecord);
    }

    @Override
    public EventRecord getEventRecordByUuid(String uuid) {
        Criteria criteria = sessionFactory.getCurrentSession().createCriteria(EventRecord.class);
        criteria.add(Restrictions.eq("uuid", uuid));
        return (EventRecord) criteria.uniqueResult();
    }

    @SuppressWarnings("unchecked")
    @Override
    public List<EventRecord> getEventRecordsByCategory(String category) {
        Criteria criteria = sessionFactory.getCurrentSession().createCriteria(EventRecord.class);
        criteria.add(Restrictions.eq("category", category));
        return criteria.list();
    }

    @SuppressWarnings("unchecked")
    @Override
    public List<EventRecord> getEventRecordsByTitle(String title) {
        Criteria criteria = sessionFactory.getCurrentSession().createCriteria(EventRecord.class);
        criteria.add(Restrictions.eq("title", title));
        return criteria.list();
    }

    @SuppressWarnings("unchecked")
    @Override
    public List<EventRecord> getEventRecordsByDateRange(Date startDate, Date endDate) {
        Criteria criteria = sessionFactory.getCurrentSession().createCriteria(EventRecord.class);
        if (startDate != null) {
            criteria.add(Restrictions.ge("timestamp", startDate)); // 'timestamp' is the date column in EventRecord
        }
        if (endDate != null) {
            criteria.add(Restrictions.le("timestamp", endDate));
        }
        return criteria.list();
    }
}