package org.openmrs.module.openmrseventrecords.api;

import org.openmrs.api.OpenmrsService;
import org.openmrs.module.openmrseventrecords.EventRecord; // Import the new domain object
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.Date;

@Transactional
public interface EventRecordService extends OpenmrsService {

    // For event records, you might not save/delete them via this module,
    // as they are typically generated by the system.
    // If you only want to expose them, you can remove save and delete methods.
    // For now, let's keep them as a skeleton, but they might not be implemented
    // if the module is purely for reading.
    EventRecord saveEventRecord(EventRecord eventRecord); // If you allow saving, otherwise remove

    EventRecord getEventRecordById(Integer id);

    List<EventRecord> getAllEventRecords();

    void deleteEventRecord(EventRecord eventRecord); // If you allow deleting, otherwise remove

    EventRecord getEventRecordByUuid(String uuid);

    // You might want to add more specific query methods, e.g., by category, title, or date range
    List<EventRecord> getEventRecordsByCategory(String category);
    List<EventRecord> getEventRecordsByTitle(String title);
    List<EventRecord> getEventRecordsByDateRange(Date startDate, Date endDate);
}